version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
    volumes:
      - "grafana:/var/lib/grafana/"
    ports:
      - 3000:3000
    user: "104"
    depends_on: 
      - loki
      - prometheus
  loki:
    image: grafana/loki:2.0.0
    volumes:
      - "loki:/loki/"
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - "/var/log:/var/log"
  prometheus:
    image: prom/prometheus:latest
    ports: 
      - "9090:9090"
  fluentd:
    build: fluentd
    volumes:
      - "./fluentd/conf/:/fluentd/etc/"
    ports: 
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - loki
volumes:
  loki:
  grafana:
